name: BossBarText
version: "${pom.version}"
api: ["1.0.13"]
author: PetteriM1
description: Simple boss bar text plugin for Nukkit
main: me.petterim1.bossbartext.Main
website: https://nukkitx.com/resources/bossbartext.38/
